return {
    'tpope/vim-fugitive',
    setup = function()
        vim.g.fugitive_no_maps = 1
    end,
    cmd = {
        'G',
        'Git',
        'Gblame',
        'Gbrowse',
        'Gedit',
        'Ggrep',
        'Glog',
        'Gmove',
        'Gremove',
        'Gstatus',
        'Gwrite',
    },
    keys = {
        { 'n', '<leader>gs', ':Gstatus<CR>' },
        { 'n', '<leader>gb', ':Gblame<CR>' },
        { 'n', '<leader>gl', ':Glog<CR>' },
        { 'n', '<leader>gd', ':Gdiff<CR>' },
        { 'n', '<leader>gc', ':Gcommit<CR>' },
        { 'n', '<leader>gp', ':Git push<CR>' },
        { 'n', '<leader>gP', ':Git pull<CR>' },
        { 'n', '<leader>gj', ':diffget //2<CR>' },
        { 'n', '<leader>gk', ':diffget //3<CR>' },
        { 'n', '<leader>ge', ':Gedit<CR>' },
        { 'n', '<leader>gw', ':Gwrite<CR>' },
        { 'n', '<leader>gR', ':Gread<CR>' },
        { 'n', '<leader>gB', ':Gbrowse<CR>' },
        { 'n', '<leader>gM', ':Gmove<CR>' },
        { 'n', '<leader>gR', ':Gremove<CR>' },
        { 'n', '<leader>gG', ':Ggrep<CR>' },
    },
    event = 'BufRead',
}
